apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: student-app

  template:
    metadata:
      labels:
        app: student-app

    spec:
      containers:
        - name: student-app
          image: student-app:v4
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: student-app-config
            - secretRef:
                name: student-app-secret

          volumeMounts:
            - name: student-storage
              mountPath: /app/data

      volumes:
        - name: student-storage
          persistentVolumeClaim:
            claimName: student-app-pvc
