apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "student-app-chart.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: student-app

  template:
    metadata:
      labels:
        app: student-app

    spec:
      containers:
        - name: student-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: student-app-config
            - secretRef:
                name: student-app-secret

          volumeMounts:
            - name: student-storage
              mountPath: /app/data

      volumes:
        - name: student-storage
          persistentVolumeClaim:
            claimName: student-app-pvc
